### ISSUE TITLE
Windows10で上手く動作しない

### ISSUE THREAD

**Issue by ggslyman** [progre/nginx-rtmp-frontend#7]

**Comment by progre** [comment]
動作確認はWindows10で行っています。
環境の症状を詳しく教えていただけますか？

**Comment by ggslyman** [comment]
OSはWindows10 Pro 64bit
nginx-rtmp-frontendは0.2.1
ngnixはWindows版の1.7.12.1 Lizard
Peercast Station 開発版 Version 2.1.1
OBSはマルチプラットフォームではない方の32bitバージョン 0.657b
SCFFは未使用

OBSから直接Cavetubeは配信OK
OBSから直接Twitchは配信OK

**Comment by ggslyman** [comment]
追記ですが、Twitchはチェックが外れている場合ストリームが流れて、チェックを入れるとエラーが出るようです。

**Comment by ggslyman** [comment]
いろいろテストしていたらTwitch回りゴチャゴチャしていて上記報告がTwitch関係間違っています
・OBSから直接TwitchはOK
・Twitchの配信にチェックを入れると接続ができない
・チェックが外れている場合は配信はつながっていない
過去の録画が流れているのを配信出来ていると勘違いしていました。

**Comment by ggslyman** [comment]
配信先をCavetube単体でも配信は開始されるが動画が表示されない

**Comment by ggslyman** [comment]
上の方のコメントを削除してまとめ直し

OSはWindows10 Pro 64bit
nginx-rtmp-frontendは0.2.1
ngnixはWindows版の1.7.12.1 Lizard
Peercast Station 開発版 Version 2.1.1
OBSはマルチプラットフォームではない方の32bitバージョン 0.657b
SCFFは未使用

PeercastとOBS同時配信でPeercast側は配信OK
フロントエンド経由でCavetubeのみは配信が開始されるが動画がストリームされない
フロントエンド経由でTwitchのみはOBSからnginxへの接続が出来ず再接続が繰り返される
OBS,Twitchともにフロントエンド経由ではなく、OBSから直接接続すると問題なく接続される
Twitchへの接続エラーはinvalid port in url "Asia:Singapore" が問題なのでFMS URLの問題だと思われる
Twitchは「Asia:Singapore」、配信キーはダッシュボードで確認できるもの
Cavetubeは「rtmp://cavestream.net/live」、配信キーはサイトから提供されているもの

**Comment by progre** [comment]
Cavetubeはこちらでも動作確認が取れていないので動作対象外としています。
TwitchはTokyoサーバーで試してもらえますか？

**Comment by ggslyman** [comment]
Cavetube了解しました
TwitchはそもそもOBSの設定の文字列をそのままではだめだという話でした
当たり前の話ですが、rtmp://live-tyo.twitch.tv/appをFMS URLに入れればOKでした
シンガポールもrtmp://live-sin.twitch.tv/appであれば配信可能でした

**Comment by progre** [comment]
解決したようなのでclose
