### ISSUE TITLE
App closes instantly

### ISSUE THREAD

**Issue by K4stor** [progre/nginx-rtmp-frontend#8]
Hi 

I was able to start the app once. But now it directly closes.
Can I somehow delete the config or rest it ?
What is the path for the config ?

Regards, 
Carsten

**Comment by progre** [comment]
You will able to find in there;
Win: C:\Users\【username】\AppData\Roaming\nginx-rtmp-frontend
Mac: /Users/【username】/Library/Application Support/nginx-rtmp-frontend

**Comment by K4stor** [comment]
Thank you so much ! This app is awesome !
